spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: entrance123
    url: jdbc:postgresql://localhost/iprwc_db2
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: com.codearise
jwtExpiration: 86400
